/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import credentials from './credentials.json'

const awsmobile = {
  Auth: {
    identityPoolId: credentials.auth.identityPoolId,
    region: credentials.auth.region,
    userPoolId: credentials.auth.userPoolId,
    userPoolWebClientId: credentials.auth.userPoolWebClientId
  },
  Storage: {
    AWSS3: {
      bucket: credentials.storage.hightier_bucket,
      region: credentials.storage.region, //OPTIONAL -  Amazon service region
    }
  },
  aws_mandatory_sign_in: 'enable' // (optional) - Users are not allowed to get the aws credentials unless they are signed in
};

export default awsmobile;
