/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  Auth: {
    identityPoolId: 'us-east-1:2ad798ce-fbbb-41e4-9758-4d3b15b37ef8', //REQUIRED - Amazon Cognito Identity Pool ID
    region: 'us-east-1', // REQUIRED - Amazon Cognito Region
    userPoolId: 'us-east-1_9rRNmdMG2', //OPTIONAL - Amazon Cognito User Pool ID
    userPoolWebClientId: '62vg7tv2knp3c21e3ae4pjaibi', //OPTIONAL - Amazon Cognito Web Client ID
  },
  Storage: {
    AWSS3: {
      bucket: 'testbucket', //REQUIRED -  Amazon S3 bucket name
      region: 'us-east-1', //OPTIONAL -  Amazon service region
    }
  },
  aws_mandatory_sign_in: 'enable' // (optional) - Users are not allowed to get the aws credentials unless they are signed in
};

export default awsmobile;
