AWSTemplateFormatVersion: "2010-09-09"
Resources:
# Monitoring
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-resourcegroups-group.html
  OnPremiseResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: on_premise_group
      Description: "On-premise resource group"
      Tags:
        - Key: businessUnit
          Value: !Ref BusinessUnit
        - Key: environment
          Value: !Ref Environment      
  ApplicationInsights:
    Type: AWS::ApplicationInsights::Application 
    Properties:
      ResourceGroupName: !Ref OnPremiseResourceGroup
      AutoConfigurationEnabled: true
